### ISSUE TITLE
Garage Door control has stopped functioning

### ISSUE THREAD

**Issue by bradsk88** [python-wink/python-wink#23] opened 2016-03-11 20:25 UTC
```

Mar 11 06:26:37 raspberrypi hass[980]: INFO:homeassistant.core:Bus:Handling <Event service_executed[L]: service_call_id=1982410576-10>
Mar 11 06:26:37 raspberrypi hass[980]: INFO:homeassistant.core:Bus:Handling <Event service_executed[L]: service_call_id=1982410576-9>
Mar 11 06:26:37 raspberrypi hass[980]: INFO:homeassistant.components.http:"POST /api/services/homeassistant/turn_on HTTP/1.1" 200 -
Mar 11 06:26:54 raspberrypi hass[980]: INFO:homeassistant.core:Bus:Handling <Event call_service[L]: service=open, service_data=entity_id=garage_door.garage_door, domain=garage_door, service_call_id=1982410576-11>
Mar 11 06:26:54 raspberrypi hass[980]: ERROR:homeassistant.core:BusHandler:Exception doing job
Mar 11 06:26:54 raspberrypi hass[980]: Traceback (most recent call last):
Mar 11 06:26:54 raspberrypi hass[980]: File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 789, in job_handler
Mar 11 06:26:54 raspberrypi hass[980]: func(arg)
Mar 11 06:26:54 raspberrypi hass[980]: File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 643, in _execute_service
Mar 11 06:26:54 raspberrypi hass[980]: service(call)
Mar 11 06:26:54 raspberrypi hass[980]: File "/usr/local/lib/python3.4/dist-packages/homeassistant/core.py", line 510, in __call__
Mar 11 06:26:54 raspberrypi hass[980]: self.func(call)
Mar 11 06:26:54 raspberrypi hass[980]: File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/garage_door/__init__.py", line 68, in handle_garage_door_service
Mar 11 06:26:54 raspberrypi hass[980]: item.open_door()
Mar 11 06:26:54 raspberrypi hass[980]: File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/garage_door/wink.py", line 65, in open_door
Mar 11 06:26:54 raspberrypi hass[980]: self.wink.set_state(1)
Mar 11 06:26:54 raspberrypi hass[980]: File "/home/pi/.homeassistant/lib/pywink/devices/standard.py", line 382, in set_state
Mar 11 06:26:54 raspberrypi hass[980]: response = self.api_interface.set_device_state(self, values)
Mar 11 06:26:54 raspberrypi hass[980]: File "/home/pi/.homeassistant/lib/pywink/api.py", line 24, in set_device_state
Mar 11 06:26:54 raspberrypi hass[980]: _id = device.device_id()
Mar 11 06:26:54 raspberrypi hass[980]: File "/home/pi/.homeassistant/lib/pywink/devices/standard.py", line 374, in device_id
Mar 11 06:26:54 raspberrypi hass[980]: return self.json_state.get('garage_door_id', self.name())
Mar 11 06:26:54 raspberrypi hass[980]: AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by w1ll1am23** [comment] 2016-03-14 20:14
@aoakeson and I have been working on this issue. It seems that the API no long likes the request we are making to desired_state. The current code gets a response of 

`{"data":null,"errors":["Unable to apply desired_state"],"pagination":{}}`

Url: https://winkapi.quirky.com/garage_doors/12345/desired_state
state: {'desired_state': {'position': 1}}

We also tried setting the desired state as a float 1.0 and not just 1, same result. 

@aoakeson gets the same result using a rest client.

**Comment by bradsk88** [comment] 2016-03-14 20:44
@w1ll1am23 What is the output of `https://api.wink.com/garage_doors/12345` ?
Under "capabilities" it should list the values that we can set

**Comment by aoakeson** [comment] 2016-03-14 20:49
@bradsk88 Here is the output:

```
{
  "data": {
    "uuid": "ed1bbc24-00d2-43e7-9994-cd9e50bef6a3",
    "desired_state": {
      "position": 0
    },
    "last_reading": {
      "position_opened": "N/A",
      "position_opened_updated_at": 1457987911.846,
      "tamper_detected_true": null,
      "tamper_detected_true_updated_at": null,
      "connection": true,
      "connection_updated_at": 1457988029.6379678,
      "position": 0,
      "position_updated_at": 1457988012.28,
      "battery": 1,
      "battery_updated_at": 1457988029.6379678,
      "fault": false,
      "fault_updated_at": 1457988029.6379678,
      "disabled": null,
      "disabled_updated_at": null,
      "control_enabled": true,
      "control_enabled_updated_at": 1457988029.6379678,
      "desired_position_updated_at": 1457988029.6673636,
      "connection_changed_at": 1457981797.1977377,
      "position_changed_at": 1457988012.28,
      "control_enabled_changed_at": 1457981797.4598124,
      "fault_changed_at": 1457981797.4598124,
      "battery_changed_at": 1457981797.4598124,
      "desired_position_changed_at": 1457988029.6673636,
      "position_opened_changed_at": 1457987911.846
    },
    "garage_door_id": "46078",
    "name": "Garage Door",
    "locale": "en_us",
    "units": {},
    "created_at": 1457981797,
    "hidden_at": null,
    "capabilities": {
      "home_security_device": true
    },
    "triggers": [],
    "manufacturer_device_model": "chamberlain_vgdo",
    "manufacturer_device_id": "5272591",
    "device_manufacturer": "chamberlain",
    "model_name": "MyQ Garage Door Controller",
    "upc_id": "532",
    "upc_code": "chamberlain_myq_gdo",
    "hub_id": null,
    "local_id": null,
    "radio_type": null,
    "linked_service_id": "310797",
    "lat_lng": [
      0,
      0
    ],
    "location": "",
    "order": null
  },
  "errors": [],
  "pagination": {}
}

```

**Comment by aoakeson** [comment] 2016-03-14 20:51
@bradsk88 @w1ll1am23 They must have removed the position capability?

**Comment by aoakeson** [comment] 2016-03-14 20:55
When I make the call for my lock: https://api.wink.com/locks/73199 it has many more capabilities: 

```

"capabilities": {
      "fields": [
        {
          "field": "connection",
          "type": "boolean",
          "mutability": "read-only"
        },
        {
          "field": "locked",
          "type": "boolean",
          "mutability": "read-write"
        },
        {
          "field": "battery",
          "type": "percentage",
          "mutability": "read-only"
        },
        {
          "field": "alarm_activated",
          "type": "boolean",
          "mutability": "read-only"
        },
        {
          "field": "beeper_enabled",
          "type": "boolean",
          "mutability": "read-write"
        },
        {
          "field": "vacation_mode_enabled",
          "type": "boolean",
          "mutability": "read-write"
        },
        {
          "field": "auto_lock_enabled",
          "type": "boolean",
          "mutability": "read-write"
        },
        {
          "field": "key_code_length",
          "type": "integer",
          "range": [
            4,
            8
          ],
          "mutability": "read-write"
        },
        {
          "field": "alarm_mode",
          "type": "string",
          "choices": [
            "alert",
            "tamper",
            "forced_entry",
            null
          ],
          "mutability": "read-write"
        },
        {
          "field": "alarm_sensitivity",
          "type": "percentage",
          "choices": [
            0.2,
            0.4,
            0.6,
            0.8,
            1
          ],
          "mutability": "read-write"
        },
        {
          "field": "alarm_enabled",
          "type": "boolean",
          "mutability": "read-write"
        }
      ],
      "home_security_device": true
    }
```

**Comment by w1ll1am23** [comment] 2016-03-14 20:59
Looks the same as the api response included when the support was originally added.

**Comment by bradsk88** [comment] 2016-03-14 21:06
This is starting to look like a Wink bug...
I'd consider getting in contact with them for clarification/suggestions.

**Comment by w1ll1am23** [comment] 2016-03-14 21:08
@aoakeson can you try to get ahold of wink? Since you own the device I am sure it will be easier. Not sure if they will help, last time I asked a question their response was "we don't support developers"

**Comment by aoakeson** [comment] 2016-03-14 22:11
Ok, ill see what i can do... Will post with response.

**Comment by aoakeson** [comment] 2016-03-15 16:09
@bradsk88 @w1ll1am23 This is the response I got......

"Sorry to say, but we do not provide any developer support. "

Ive replied with email asking who I can email, but Im not holding my breath on anything.... My assumption is that this is affecting everyone using the wink garage door.  Is the best way to figure this out just posting on gitter?

**Comment by bradsk88** [comment] 2016-03-15 23:23
Bummer.  I assume you can still control it via the wink app?

**Comment by aoakeson** [comment] 2016-03-16 00:06
Yea I can control it through the app. It doesn't make sense though it seems as if the app should use the same Api?

**Comment by bradsk88** [comment] 2016-03-16 00:33
This is a stretch but I'd be curious to see what would happen if you would un-pair the garage door opener and re-pair it with the Wink hub.

**Comment by aoakeson** [comment] 2016-03-16 17:09
Yea, I tried that and about everything else.  Factory resetting the controller, as well as the app.  No dice.  

I did just get an email from wink:

"As part of our agreement with Chamberlain, third-party access to control Chamberlain garage doors has been restricted. Please contact Chamberlain directly to inquire about permissions."

Ill try contacting them.

**Comment by bradsk88** [comment] 2016-03-16 18:02
Ouch.  Thanks, Chamberlain :disappointed:

**Comment by aoakeson** [comment] 2016-03-17 16:06
@bradsk88 I assume you are aware of what @w1ll1am23 found, do we still need to keep this issue open?  Its now working for me with the android hack.

**Comment by bradsk88** [comment] 2016-03-17 16:32
I'll leave it open.  I'm still going to try to improve the way python-wink fails under this circumstance.

**Comment by aoakeson** [comment] 2016-03-17 16:35
Ok. Sounds good. One thing Ive been noticing, is that if I manually close the garage door, HA doesnt recognize this, and HA still marks it as opened.  Is this something that can be watched by HA if it wasnt opened or closed by HA

**Comment by bradsk88** [comment] 2016-03-17 16:58
Yep.  The open/closed state should get updated.  Probably a bug in this project.

**Comment by aoakeson** [comment] 2016-03-17 21:20
This might not be a bug.  I just pulled up the wink app, and its saying my garage door is open

While the chaimberlin app is saying it is closed.  (This is correct) I wonder if this is a wink bug?

**Comment by bradsk88** [comment] 2016-11-29 20:36
@aoakeson Did this ever start working for you?

**Comment by aoakeson** [comment] 2016-11-29 22:16
I havent been using HA to control my garage because of this, but I will integrate wink again into HA, and update you with results.

**Comment by Custos** [comment] 2017-01-04 09:20
If you dig hard enough, you can find some python scripts that allow you to open and close the door  -- then you can choose whether you want to use home-assistant.io, or some other mechanism to manage the door.  

What I can't figure out is how https://winkathome.net is able to open and close the door if the API blocks it.  Maybe @trunzoc can give a hint!?

**Comment by w1ll1am23** [comment] 2017-01-04 11:34
@custos wink@home is working because it is using a token provided by either the android or iOS client secret and ID. This same thing can be done with homeassistant. Basically it tricks the api into thinking you are using the wink app. 

Take a look here for more details https://community.home-assistant.io/t/myq-componenet-issues/1860/155

**Comment by trunzoc** [comment] 2017-01-05 05:53
Wink@Home uses its own set of API creds.  It does not use the Android ones.  When you login from Wink@Home, the wink api login page actually contains the Wink@Home info because Wink Associated a specific login page with Wink@Home via my on set of creds.  It's the same with the subscription stuff used for the "Connections" feature of Wink@Home (basically, a way to send device events to IFTTT or some other API service).  If I was using Android creds, Wink@Home would not be able to get those subscriptions as it would conflict with the mobile App.

I'm really not sure what would be different about Wink@Home that let's it open doors, when others can't.  :(

**Comment by w1ll1am23** [comment] 2017-01-05 11:50
@turnzoc thanks for getting back to us. Interesting! So I have proxies the android app and watched all the requests it makes, it isn't doing anything different from python-wink, but use its token and use a custom user-agent. Python-wink works when using the android token. 

They only thing that makes sense to me would be they are blacklisting tokens and not white listing. Somehow they just forgot to block the wink@home token?

**Comment by w1ll1am23** [comment] 2017-01-11 13:56
@trunzoc Based on the file here https://github.com/trunzoc/WinkAtHome/blob/4ce4d32badb21b33abc495e9d755adc2901f72ec/WinkAtHome/Web.config it looks like on lines 17 and 18 you have the API credentials configured to the Android apps client_id and client_secret.

Having said that, I have noticed other things that don't make since. For example all devices in wink@home show a field in their JSON called "object_type" this would be sweet to have in python-wink, but it doesn't show up. I even tried using the token from wink@home and I still don't see those fields. I am wondering if it has anything to do with the user-agent that is being sent. Is it possible for you to tell me what user-agent you are sending when making api requests to wink?

When I send the user-agent that is used in the Android app, I not get the object_type field.

**Comment by cbulock** [comment] 2017-01-11 14:27
I've had to use the following user agent to get that extra data from the api

`Manufacturer/Darwin node/0.10.30 Wink/3.1.0`

**Comment by w1ll1am23** [comment] 2017-01-11 14:33
@cbulock sweet, thanks. Just tried that it and it works too. Changed it a bit and this seems to still work.

```
Manufacturer/python-wink Wink/4
```

**Comment by trunzoc** [comment] 2017-01-15 01:31
You need to remember that the Wink@Home code here on GitHub is extremely old.  It was designed as a standalone app to run on a person's PC.  It was turning into a nightmare for support because so many people have so many different windows and IIS configurations. Not to mention that some people really have no understanding of IIS at all.  I chose to retire the code on GitHub and change it to a public website that I host myself for all to use.

So yes, the code here on GitHub DOES use the Android credentials, but the actual Wink@Home website, https://winkathome.net (not accessible right this second. Cert expired and waiting for the new one to get issued) does not.  

Maybe the "Darwin" header is what allows my personal creds to unblock/open doors.

I completely forgot about Darwin.  It was given to me by a Wink dev so long ago that I forgot it was how the expanded JSON fields were returned.

**Comment by w1ll1am23** [comment] 2017-07-08 14:23
I don't think this issue needs to stay open any longer. There isn't anything that can be done to get this working with python-wink other than the know work around of using official android/ios client_id and secrets. Other garage doors like the generic zwave GoControl will work and if Chamberlain ever removes the restriction they will start working as well.

**Closed as completed by w1ll1am23** 2017-07-08 14:23 UTC
