### ISSUE TITLE
Wink.py/fan.py errors adding GE in-wall fan (update #105)

### ISSUE THREAD

**Issue by GaryOkie** [python-wink/python-wink#107] opened 2018-06-27 20:56 UTC
I have two ceiling fans paired with Wink using the GE in-wall fan control.   Both were working  in Hassio 70.1  (as light.xxxxx entities), but upon updating to 72.1 today, only one is working (now as fan.xxxx).   (per Wink update #105 @vickyg3)

Here is the error which indicates something amiss with reading brightness/fan speed.   The fan that failed to be integrated properly was currently at or near zero so as to get the lowest possible speed.

`2018-06-27 14:25:18 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved

Traceback (most recent call last):
 
 File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 326, in _async_add_entity
    await entity.async_update_ha_state()
  
File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 215, in async_update_ha_state
    attr = self.state_attributes or {}
 
 File "/usr/lib/python3.6/site-packages/homeassistant/components/fan/__init__.py", line 315, in state_attributes
    if not hasattr(self, prop):
  
File "/usr/lib/python3.6/site-packages/homeassistant/components/fan/wink.py", line 66, in speed
    current_wink_speed = self.wink.current_fan_speed()
  
File "/usr/lib/python3.6/site-packages/pywink/devices/fan.py", line 129, in current_fan_speed
    return self._to_speed[self._last_reading.get('brightness', 0.33)]
KeyError: 0.0`

-----------------------
Note:  group.all_fans lists both fans ( fan.bedroom_ceiling_fan,   fan.den_ceiling_fan)
but "fan.den_ceiling_fan" did not exist as an entity when I first looked into this problem. 

UPDATE:
I have just now set this fan to full speed via the Wink interface, and lo and behold, fan.den_ceiling_fan is now listed as an entity and shows up on the dashboard!   It appears that the errors listed above have also stopped.

**Comment by vickyg3** [comment] 2018-06-28 16:49
Based on your latest update, it looks like it works and is no longer a bug?

**Comment by GaryOkie** [comment] 2018-06-28 17:00
Oh, there is still a significant bug.   Did you not see my last post on #105 with all the details?

My wife prefers to use the simple Wink GUI to control the fans, and as long as she doesn't move the Wink fan slider all the way to zero, there is no problem with this HA update.   But any time the Wink slider is set to zero, wink/fan.py crashes while handling the brightness/speed setting and the fans disappear from Hassio. 

I also mentioned that you should be able to duplicate this scenario.

**Comment by vickyg3** [comment] 2018-06-28 17:07
Ah, sorry, i got it now. I misread your update then. I think i understand what is going on now. I will try to see if i can duplicate the scenario. :)

**Comment by vickyg3** [comment] 2018-06-28 17:39
I was able to reproduce the scenario and i have pushed a patch (PR #108) to fix the issue. Once it is merged, i will update home assistant as well.

Thanks for the patience and detailed resposnes. :)

**Comment by GaryOkie** [comment] 2018-06-28 17:47
Thank you for taking care of it so quickly!

**Closed as completed** 2018-06-28 23:35 UTC
